version: '2.1'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.29
    ports:
      - 3307:3306
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    restart: always
    env_file: ./.env
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$MYSQLDB_ROOT_PASSWORD' ]
      interval: 10s
      timeout: 2s
      retries: 10
  app:
    image: 'api-rest:latest'
    build:
      context: .
    container_name: app
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: always
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL : jdbc:mysql://mysqldb:3306/cambio_divisa?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME : $MYSQLDB_USER
      SPRING_DATASOURCE_PASSWORD : $MYSQLDB_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO : create
      SPRING_JPA_SHOW_SQL : true
    ports:
      - 8082:8082